spring:
  flyway:
    enabled: false
  datasource:
    url:
    username:
    password:
  jpa:
    properties:
      generate_statistics: true
      jdbc:
        batch_size: 100
        order_inserts: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

