spring:
  datasource:
    url: jdbc:h2:mem:twitterchallange;MODE=mysql;INIT=CREATE SCHEMA IF NOT EXISTS "public"
    username: root
    password:
  jpa:
    properties:
      jdbc:
        batch_size: 100
        order_inserts: true
server:
  port: 8090
