# Default properties file
spring:
  profiles:
    active: ${SCOPE_SUFFIX} # Comma-separated list of active profiles. Can be overridden by a command line switch.
  web:
    resources:
      add-mappings: false

server:
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.

springdoc:
  packages-to-scan: twitter.challenge.espenia.entrypoint
  show-actuator: true
  swagger-ui:
    operations-sorter: alpha
    disable-swagger-default-url: true

app:
  title: twitter-challange-espenia
  description: '@project.description@'
  version: '@project.version@'

