spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:twitterchallange;MODE=mysql;INIT=CREATE SCHEMA IF NOT EXISTS "public"
    username: root
    password:
  jpa:
    properties:
      generate_statistics: true
      jdbc:
        batch_size: 100
        order_inserts: true
      hibernate:
        show_sql: true
