{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "twitter-challange-espenia",
    "description" : "@project.description@",
    "version" : "@project.version@"
  },
  "servers" : [ {
    "url" : "http://localhost:8080",
    "description" : "Scope local"
  } ],
  "paths" : {
    "/api/users/{id}" : {
      "get" : {
        "tags" : [ "user-controller" ],
        "operationId" : "getUser",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UserResponse"
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "user-controller" ],
        "operationId" : "updateUser",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UserUpdateRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UserResponse"
                }
              }
            }
          }
        }
      },
      "delete" : {
        "tags" : [ "user-controller" ],
        "operationId" : "deleteUser",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        }
      }
    },
    "/api/users" : {
      "post" : {
        "tags" : [ "user-controller" ],
        "operationId" : "createUser",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/UserRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UserResponse"
                }
              }
            }
          }
        }
      }
    },
    "/ping" : {
      "get" : {
        "tags" : [ "ping-controller" ],
        "operationId" : "ping",
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/username/{username}" : {
      "get" : {
        "tags" : [ "user-controller" ],
        "operationId" : "getUserByUsername",
        "parameters" : [ {
          "name" : "username",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "$ref" : "#/components/schemas/UserResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "UserUpdateRequest" : {
        "type" : "object",
        "properties" : {
          "display_name" : {
            "maxLength" : 100,
            "minLength" : 0,
            "type" : "string"
          },
          "password" : {
            "maxLength" : 100,
            "minLength" : 8,
            "type" : "string"
          },
          "bio" : {
            "maxLength" : 500,
            "minLength" : 0,
            "type" : "string"
          }
        }
      },
      "UserResponse" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "username" : {
            "type" : "string"
          },
          "display_name" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "bio" : {
            "type" : "string"
          },
          "created_at" : {
            "type" : "string",
            "format" : "date-time"
          },
          "updated_at" : {
            "type" : "string",
            "format" : "date-time"
          }
        }
      },
      "UserRequest" : {
        "required" : [ "bio", "display_name", "email", "password", "username" ],
        "type" : "object",
        "properties" : {
          "username" : {
            "maxLength" : 50,
            "minLength" : 3,
            "type" : "string"
          },
          "display_name" : {
            "maxLength" : 100,
            "minLength" : 0,
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "password" : {
            "maxLength" : 100,
            "minLength" : 8,
            "type" : "string"
          },
          "bio" : {
            "maxLength" : 500,
            "minLength" : 0,
            "type" : "string"
          }
        }
      }
    }
  }
}